
project:
  type: website

freeze: true

website:
  title: "probably wrong"

  navbar:
    pinned: true

    right:
    - text: About
      href: about.qmd
    - icon: github
      href: https://github.com/hendr1km

  page-footer: 
    left: |
      “All models are wrong, but some are useful” - George E. P. Box
    center: 
       - text: "About"
         href: about.qmd
    right:
      - icon: github
        href: https://github.com/hendr1km

format:
  html:
    theme:
      light: [cosmo, styles/light.scss]

editor: visual

resources:
  - CNAME
