
project:
  type: website

freeze: true

website:
  title: "probably wrong"

  navbar:
    pinned: true

    right:
    - text: About
      href: about.qmd
    - icon: github
      href: https://github.com/hendr1km

format:
  html:
    theme:
      light: [cosmo, styles/light.scss]
      dark: [cosmo, styles/dark.scss]

editor: visual

