
project:
  type: website

freeze: true

website:
  cookie-consent: true
  google-analytics:
    tracking-id: "G-3CMB0C0E8X"
    anonymize-ip: true

  title: "probably wrong"

  navbar:
    pinned: true

    right:
    - text: About
      href: about.qmd
    - icon: github
      href: https://github.com/hendr1km

  page-footer: 
    center:
      “All models are wrong, but some are useful” - George E. P. Box

format:
  html:
    theme:
      light: [cosmo, styles/light.scss]

editor: visual

resources:
  - CNAME
